"""Error code registry for workflow and activities."""

from __future__ import annotations

from enum import Enum


class ErrorCode(str, Enum):
    # Generic
    INTERNAL_ERROR = "INTERNAL_ERROR"
    INVALID_INPUT = "INVALID_INPUT"
    CANCELLED = "CANCELLED"

    # Parse phase
    PDF_PARSE_FAILED = "PDF_PARSE_FAILED"
    PDF_EMPTY_CONTENT = "PDF_EMPTY_CONTENT"

    # Skeleton phase
    SKELETON_BUILD_FAILED = "SKELETON_BUILD_FAILED"

    # Refinement phase
    PROVIDER_RATE_LIMIT = "PROVIDER_RATE_LIMIT"
    PROVIDER_TIMEOUT = "PROVIDER_TIMEOUT"
    PROVIDER_NETWORK_ERROR = "PROVIDER_NETWORK_ERROR"
    PROVIDER_RESPONSE_INVALID = "PROVIDER_RESPONSE_INVALID"
    REFINE_EMPTY_RESULT = "REFINE_EMPTY_RESULT"
    REFINE_EXHAUSTED = "REFINE_EXHAUSTED"

    # Integrity/export phase
    INTEGRITY_INCOMPLETE = "INTEGRITY_INCOMPLETE"
    EXPORT_ASSEMBLY_FAILED = "EXPORT_ASSEMBLY_FAILED"
    EXPORT_PERSIST_FAILED = "EXPORT_PERSIST_FAILED"


RETRYABLE_CODES = {
    ErrorCode.PROVIDER_RATE_LIMIT,
    ErrorCode.PROVIDER_TIMEOUT,
    ErrorCode.PROVIDER_NETWORK_ERROR,
}

NON_RETRYABLE_CODES = {
    ErrorCode.INVALID_INPUT,
    ErrorCode.PROVIDER_RESPONSE_INVALID,
}
